/* Write your PL/SQL query statement below */
SELECT TEACHER_ID, COUNT(DISTINCT SUBJECT_ID) CNT
FROM TEACHER
WHERE TEACHER_ID IN (
    SELECT DISTINCT TEACHER_ID
    FROM TEACHER
)
GROUP BY TEACHER_ID;