/* Write your PL/SQL query statement below */
  SELECT ID,
         SUM (CASE WHEN UPPER (MONTH) = 'JAN' THEN REVENUE ELSE NULL END)
             JAN_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'FEB' THEN REVENUE ELSE NULL END)
             FEB_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'MAR' THEN REVENUE ELSE NULL END)
             MAR_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'APR' THEN REVENUE ELSE NULL END)
             APR_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'MAY' THEN REVENUE ELSE NULL END)
             MAY_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'JUN' THEN REVENUE ELSE NULL END)
             JUN_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'JUL' THEN REVENUE ELSE NULL END)
             JUL_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'AUG' THEN REVENUE ELSE NULL END)
             AUG_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'SEP' THEN REVENUE ELSE NULL END)
             SEP_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'OCT' THEN REVENUE ELSE NULL END)
             OCT_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'NOV' THEN REVENUE ELSE NULL END)
             NOV_REVENUE,
         SUM (CASE WHEN UPPER (MONTH) = 'DEC' THEN REVENUE ELSE NULL END)
             DEC_REVENUE
    FROM DEPARTMENT
GROUP BY ID;