/* Write your PL/SQL query statement below */
SELECT  TO_CHAR(trans_date, 'YYYY-MM') AS MONTH,
        COUNTRY,
        COUNT(*) TRANS_COUNT,
        SUM(CASE WHEN UPPER(STATE) = 'APPROVED' THEN 1 ELSE 0 END) AS APPROVED_COUNT,
        SUM(AMOUNT) TRANS_TOTAL_AMOUNT,
        SUM(CASE WHEN UPPER(STATE) = 'APPROVED' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(trans_date, 'YYYY-MM'), COUNTRY;