/* Write your PL/SQL query statement below */
SELECT TO_CHAR(SELL_DATE, 'YYYY-MM-DD') SELL_DATE,
COUNT(DISTINCT PRODUCT) NUM_SOLD,
LISTAGG(PRODUCT, ',') WITHIN GROUP (ORDER BY PRODUCT) PRODUCTS
FROM (
    SELECT DISTINCT PRODUCT, SELL_DATE
    FROM ACTIVITIES
)
GROUP BY SELL_DATE
ORDER BY SELL_DATE ASC;