SELECT p.PRODUCT_ID, NVL(ROUND(SUM(p.PRICE * us.UNITS) / SUM(us.UNITS), 2), 0) AVERAGE_PRICE
FROM PRICES p
LEFT OUTER JOIN UNITSSOLD us
ON us.PURCHASE_DATE BETWEEN p.START_DATE AND p.END_DATE
AND p.PRODUCT_ID = us.PRODUCT_ID
GROUP BY p.PRODUCT_ID;