/* Write your PL/SQL query statement below */
  SELECT P.PRODUCT_ID, P.PRODUCT_NAME
    FROM SALES S LEFT JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
  HAVING     MIN (S.SALE_DATE) >= TO_DATE ('2019-01-01', 'YYYY-MM-DD')
         AND MAX (S.SALE_DATE) <= TO_DATE ('2019-03-31', 'YYYY-MM-DD');