/* Write your PL/SQL query statement below */
  SELECT U.NAME, SUM (T.AMOUNT) BALANCE
    FROM USERS U JOIN TRANSACTIONS T ON U.ACCOUNT = T.ACCOUNT
GROUP BY U.NAME, U.ACCOUNT
  HAVING SUM (T.AMOUNT) > 10000