/* Write your PL/SQL query statement below */
SELECT p.PROJECT_ID, ROUND(AVG(e.EXPERIENCE_YEARS), 2) AVERAGE_YEARS
FROM PROJECT p
JOIN EMPLOYEE e
ON p.EMPLOYEE_ID = e.EMPLOYEE_ID
GROUP BY p.PROJECT_ID;