SELECT 
    s.STUDENT_ID, 
    s.STUDENT_NAME, 
    sj.SUBJECT_NAME, 
    COUNT(e.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS s
CROSS JOIN SUBJECTS sj
LEFT JOIN EXAMINATIONS e 
    ON s.STUDENT_ID = e.STUDENT_ID AND sj.SUBJECT_NAME = e.SUBJECT_NAME
GROUP BY s.STUDENT_ID, s.STUDENT_NAME, sj.SUBJECT_NAME
ORDER BY s.STUDENT_ID, sj.SUBJECT_NAME;