/* Write your PL/SQL query statement below */
  SELECT LB.BOOK_ID,
         LB.TITLE,
         LB.AUTHOR,
         LB.GENRE,
         LB.PUBLICATION_YEAR,
         COUNT (BR.BOOK_ID)     AS CURRENT_BORROWERS
    FROM LIBRARY_BOOKS LB JOIN BORROWING_RECORDS BR ON LB.BOOK_ID = BR.BOOK_ID
   WHERE BR.RETURN_DATE IS NULL
GROUP BY LB.BOOK_ID,
         LB.TITLE,
         LB.AUTHOR,
         LB.GENRE,
         LB.PUBLICATION_YEAR,
         LB.TOTAL_COPIES
  HAVING COUNT(LB.BOOK_ID) = LB.TOTAL_COPIES
  ORDER BY CURRENT_BORROWERS DESC, LB.TITLE ASC;