SELECT 
    r.CONTEST_ID,
    ROUND((COUNT(DISTINCT r.USER_ID) * 100.0) / (SELECT COUNT(*) FROM USERS), 2) AS PERCENTAGE
FROM 
    REGISTER r
GROUP BY 
    r.CONTEST_ID
ORDER BY 
    PERCENTAGE DESC,
    r.CONTEST_ID ASC;