/* Write your PL/SQL query statement below */
SELECT TO_CHAR(ACTIVITY_DATE, 'YYYY-MM-DD') DAY,
COUNT(DISTINCT USER_ID) ACTIVE_USERS 
FROM ACTIVITY 
WHERE ACTIVITY_DATE BETWEEN TO_DATE('2019-06-28', 'YYYY-MM-DD') AND TO_DATE('2019-07-27', 'YYYY-MM-DD') 
GROUP BY ACTIVITY_DATE;