/* Write your PL/SQL query statement below */
SELECT SP.NAME
FROM SALESPERSON SP
MINUS
SELECT SP.NAME
FROM SALESPERSON SP
JOIN ORDERS O
ON SP.SALES_ID = O.SALES_ID
WHERE O.COM_ID IN (
    SELECT COM_ID
    FROM COMPANY
    WHERE NAME = 'RED'
);