/* Write your PL/SQL query statement below */
SELECT E1.EMPLOYEE_ID,
E1.NAME,
COUNT(
    E2.EMPLOYEE_ID
) REPORTS_COUNT,
ROUND(
    AVG (
        E2.AGE
    )
) AVERAGE_AGE
FROM EMPLOYEES E1
JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.REPORTS_TO
GROUP BY E1.EMPLOYEE_ID, E1.NAME
ORDER BY E1.EMPLOYEE_ID;