/* Write your PL/SQL query statement below */
  SELECT U.NAME,
         SUM (CASE WHEN DISTANCE IS NOT NULL THEN DISTANCE ELSE 0 END)    TRAVELLED_DISTANCE
    FROM USERS U LEFT JOIN RIDES R ON U.ID = R.USER_ID
GROUP BY U.NAME, U.ID
ORDER BY TRAVELLED_DISTANCE DESC, NAME ASC